#!/usr/bin/env bash
# If the gl server segfaults, it probably just can't find the conf file.
rm conf/opc_layout.json
java -cp "target/udder-1.0-SNAPSHOT.jar:lib/simple-5.1.5.jar:lib/boon-0.23.jar" com.coillighting.udder.Main conf/patch_sheet.json conf/opc_layout.json

