#!/usr/bin/env bash

# Run Udder from the Maven-built jar. You must first build it. If you don't
# know how, use serve_from_dist instead.
#
# We add the option '-Xverify:none' so that we are allowed to attach an invasive
# profiler like VisualVM when analyzing Udder's performance.
#
# If the gl server segfaults, it probably just can't find the opc_layout.json
# conf file.

PROPERTIES="conf/dairy.properties"

if [[ ! -f $PROPERTIES ]] ; then
    echo "ERROR: Udder properties file not found: $PROPERTIES"
    echo "If this is your first time running udder, copy conf/development.properties.example"
    echo "to your own local $PROPERTIES and try again."
    exit 1
fi

java -Xverify:none -cp "target/udder-0.4.1-SNAPSHOT.jar:lib/simple-5.1.5.jar:lib/boon-0.23.jar" com.coillighting.udder.Main $PROPERTIES
