#!/usr/bin/env bash

# Run Udder from the prebuild jar.
#
# We build these all-in-one lib-bundled jars in IntelliJ. They let you run
# Udder's example scene without setting up your build environment.
#
# We add the option '-Xverify:none' so that we are allowed to attach an invasive
# profiler like VisualVM when analyzing Udder's performance.
#
# If the gl server segfaults, it probably just can't find the opc_layout.json
# conf file.

java -Xverify:none -cp "dist/udder-0.4.1.jar" com.coillighting.udder.Main conf/dairy.properties
