#!/usr/bin/env bash
# Serve Udder from a jar built locally using the Maven command-line tasks.
# Uncomment the patch the opc_layout.json to regenerate the opc gl server conf.
# If the gl server segfaults, it probably just can't find the conf file.
java -cp "target/udder-0.4-SNAPSHOT.jar:lib/simple-5.1.5.jar:lib/boon-0.23.jar" com.coillighting.udder.Main conf/dairy.properties # conf/opc_layout.json
