#!/usr/bin/env bash

# Run Udder from the prebuild jar.
#
# We build these all-in-one lib-bundled jars in IntelliJ. They let you run
# Udder's example scene without setting up your build environment.
#
# We add the option '-Xverify:none' so that we are allowed to attach an invasive
# profiler like VisualVM when analyzing Udder's performance.
#
# If the gl server segfaults, it probably just can't find the opc_layout.json
# conf file.

PROPERTIES="conf/dairy.properties"

if [[ ! -f $PROPERTIES ]] ; then
    echo "ERROR: Udder properties file not found: $PROPERTIES"
    echo "If this is your first time running udder, copy conf/development.properties.example"
    echo "to your own local $PROPERTIES and try again."
    exit 1
fi

java -Xverify:none -cp "dist/udder-0.4.2.jar" com.coillighting.udder.Main $PROPERTIES
