#!/usr/bin/env sh
echo "Tinting the ENTIRE show with a simulated medium amber filter."
echo "Don't forget to turn this off with gel_off.sh."
curl -X POST -d @json/level_full.json http://localhost:8080/mixer0/layer22
curl -X POST -d @json/amber_gel.json http://localhost:8080/mixer0/layer22/effect
