#!/usr/bin/env sh
echo "Tinting the ENTIRE show with a simulated moon blue filter."
echo "This color will probably require fine-tuning on site."
echo "Don't forget to turn this off with gel_off.sh."
curl -X POST -d @json/cold_gel.json http://localhost:8080/mixer0/layer22/effect
curl -X POST -d @json/level_full.json http://localhost:8080/mixer0/layer22
