git mv amber_gel_on.sh                       amber_gel_on
git mv blackout.sh blackout
git mv blue_red_woven.sh blue_red_woven
git mv cold_gel_on.sh cold_gel_on
git mv dashes.sh dashes
git mv gel_off.sh gel_off
git mv layer_10pct.sh layer_10pct
git mv layer_25pct.sh layer_25pct
git mv layer_55pct.sh layer_55pct
git mv layer_90pct.sh layer_90pct
git mv layer_full.sh layer_full
git mv layer_off.sh layer_off
git mv light_first_pixel.sh light_first_pixel
git mv magenta_gold_woven.sh magenta_gold_woven
git mv mixer_55pct.sh mixer_55pct
git mv mixer_full.sh mixer_full
git mv mixer_off.sh mixer_off
git mv pastel_rainbow.sh pastel_rainbow
git mv purple_green_woven.sh purple_green_woven
git mv query_effect.sh query_effect
git mv query_layer.sh query_layer
git mv query_mixer.sh query_mixer
git mv restart_woven.sh restart_woven
git mv scroll_blip.sh scroll_blip
git mv scroll_pastel_rainbow.sh scroll_pastel_rainbow
git mv shuffler_disabled.sh shuffler_disabled
git mv shuffler_enabled.sh shuffler_enabled
git mv shuffler_fast.sh shuffler_fast
git mv shuffler_slow.sh shuffler_slow
git mv switch_layers.sh switch_layers
git mv test_broken_payload_key.sh test_broken_payload_key
git mv test_broken_payload_syntax.sh test_broken_payload_syntax
git mv test_broken_payload_value.sh test_broken_payload_value
git mv test_broken_route_effect.sh test_broken_route_effect
git mv test_broken_route_layer.sh test_broken_route_layer
git mv test_broken_route_mixer.sh test_broken_route_mixer
git mv test_broken_state_key.sh test_broken_state_key
git mv texture_auto.sh texture_auto
git mv texture_manual.sh texture_manual
git mv worklight_off.sh worklight_off
git mv worklight_white.sh worklight_white
git mv woven.sh woven
