#!/usr/bin/env sh
echo "Switching off the worklight, and blacking out its layer."
curl -X POST -d @json/level_off.json http://localhost:8080/mixer0/layer0
curl -X POST -d @json/black_background.json http://localhost:8080/mixer0/layer0/effect
